/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Apteco.ApiSystemAnalyser.ApiClient.Client.SwaggerDateConverter;

namespace Apteco.ApiSystemAnalyser.ApiClient.Model
{
    /// <summary>
    /// Summary information for a list result
    /// </summary>
    [DataContract]
    public partial class ListResultSummary :  IEquatable<ListResultSummary>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListResultSummary" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ListResultSummary() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListResultSummary" /> class.
        /// </summary>
        /// <param name="Id">The id for this result (required).</param>
        /// <param name="ListUpdateId">The id of the update (list version) that this result was calculated with (required).</param>
        /// <param name="Timestamp">The date and time that this result was calculated (required).</param>
        /// <param name="FastStatsBuildDate">The date and time that the FastStats system used to calculate this result was built (required).</param>
        /// <param name="User">The user that triggered the calculation of this result (required).</param>
        /// <param name="NettCounts">The set of overall counts for this result (required).</param>
        /// <param name="UrnFilePath">If a URN file was generated as part of this result then this will be its path within the FastStats system (required).</param>
        public ListResultSummary(int? Id = default(int?), int? ListUpdateId = default(int?), DateTime? Timestamp = default(DateTime?), DateTime? FastStatsBuildDate = default(DateTime?), UserDisplayDetails User = default(UserDisplayDetails), List<Count> NettCounts = default(List<Count>), string UrnFilePath = default(string))
        {
            // to ensure "Id" is required (not null)
            if (Id == null)
            {
                throw new InvalidDataException("Id is a required property for ListResultSummary and cannot be null");
            }
            else
            {
                this.Id = Id;
            }
            // to ensure "ListUpdateId" is required (not null)
            if (ListUpdateId == null)
            {
                throw new InvalidDataException("ListUpdateId is a required property for ListResultSummary and cannot be null");
            }
            else
            {
                this.ListUpdateId = ListUpdateId;
            }
            // to ensure "Timestamp" is required (not null)
            if (Timestamp == null)
            {
                throw new InvalidDataException("Timestamp is a required property for ListResultSummary and cannot be null");
            }
            else
            {
                this.Timestamp = Timestamp;
            }
            // to ensure "FastStatsBuildDate" is required (not null)
            if (FastStatsBuildDate == null)
            {
                throw new InvalidDataException("FastStatsBuildDate is a required property for ListResultSummary and cannot be null");
            }
            else
            {
                this.FastStatsBuildDate = FastStatsBuildDate;
            }
            // to ensure "User" is required (not null)
            if (User == null)
            {
                throw new InvalidDataException("User is a required property for ListResultSummary and cannot be null");
            }
            else
            {
                this.User = User;
            }
            // to ensure "NettCounts" is required (not null)
            if (NettCounts == null)
            {
                throw new InvalidDataException("NettCounts is a required property for ListResultSummary and cannot be null");
            }
            else
            {
                this.NettCounts = NettCounts;
            }
            // to ensure "UrnFilePath" is required (not null)
            if (UrnFilePath == null)
            {
                throw new InvalidDataException("UrnFilePath is a required property for ListResultSummary and cannot be null");
            }
            else
            {
                this.UrnFilePath = UrnFilePath;
            }
        }
        
        /// <summary>
        /// The id for this result
        /// </summary>
        /// <value>The id for this result</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// The id of the update (list version) that this result was calculated with
        /// </summary>
        /// <value>The id of the update (list version) that this result was calculated with</value>
        [DataMember(Name="listUpdateId", EmitDefaultValue=false)]
        public int? ListUpdateId { get; set; }

        /// <summary>
        /// The date and time that this result was calculated
        /// </summary>
        /// <value>The date and time that this result was calculated</value>
        [DataMember(Name="timestamp", EmitDefaultValue=false)]
        public DateTime? Timestamp { get; set; }

        /// <summary>
        /// The date and time that the FastStats system used to calculate this result was built
        /// </summary>
        /// <value>The date and time that the FastStats system used to calculate this result was built</value>
        [DataMember(Name="fastStatsBuildDate", EmitDefaultValue=false)]
        public DateTime? FastStatsBuildDate { get; set; }

        /// <summary>
        /// The user that triggered the calculation of this result
        /// </summary>
        /// <value>The user that triggered the calculation of this result</value>
        [DataMember(Name="user", EmitDefaultValue=false)]
        public UserDisplayDetails User { get; set; }

        /// <summary>
        /// The set of overall counts for this result
        /// </summary>
        /// <value>The set of overall counts for this result</value>
        [DataMember(Name="nettCounts", EmitDefaultValue=false)]
        public List<Count> NettCounts { get; set; }

        /// <summary>
        /// If a URN file was generated as part of this result then this will be its path within the FastStats system
        /// </summary>
        /// <value>If a URN file was generated as part of this result then this will be its path within the FastStats system</value>
        [DataMember(Name="urnFilePath", EmitDefaultValue=false)]
        public string UrnFilePath { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListResultSummary {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ListUpdateId: ").Append(ListUpdateId).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  FastStatsBuildDate: ").Append(FastStatsBuildDate).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  NettCounts: ").Append(NettCounts).Append("\n");
            sb.Append("  UrnFilePath: ").Append(UrnFilePath).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListResultSummary);
        }

        /// <summary>
        /// Returns true if ListResultSummary instances are equal
        /// </summary>
        /// <param name="input">Instance of ListResultSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListResultSummary input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ListUpdateId == input.ListUpdateId ||
                    (this.ListUpdateId != null &&
                    this.ListUpdateId.Equals(input.ListUpdateId))
                ) && 
                (
                    this.Timestamp == input.Timestamp ||
                    (this.Timestamp != null &&
                    this.Timestamp.Equals(input.Timestamp))
                ) && 
                (
                    this.FastStatsBuildDate == input.FastStatsBuildDate ||
                    (this.FastStatsBuildDate != null &&
                    this.FastStatsBuildDate.Equals(input.FastStatsBuildDate))
                ) && 
                (
                    this.User == input.User ||
                    (this.User != null &&
                    this.User.Equals(input.User))
                ) && 
                (
                    this.NettCounts == input.NettCounts ||
                    this.NettCounts != null &&
                    this.NettCounts.SequenceEqual(input.NettCounts)
                ) && 
                (
                    this.UrnFilePath == input.UrnFilePath ||
                    (this.UrnFilePath != null &&
                    this.UrnFilePath.Equals(input.UrnFilePath))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.ListUpdateId != null)
                    hashCode = hashCode * 59 + this.ListUpdateId.GetHashCode();
                if (this.Timestamp != null)
                    hashCode = hashCode * 59 + this.Timestamp.GetHashCode();
                if (this.FastStatsBuildDate != null)
                    hashCode = hashCode * 59 + this.FastStatsBuildDate.GetHashCode();
                if (this.User != null)
                    hashCode = hashCode * 59 + this.User.GetHashCode();
                if (this.NettCounts != null)
                    hashCode = hashCode * 59 + this.NettCounts.GetHashCode();
                if (this.UrnFilePath != null)
                    hashCode = hashCode * 59 + this.UrnFilePath.GetHashCode();
                return hashCode;
            }
        }
    }

}
