/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Apteco.ApiSystemAnalyser.ApiClient.Client;
using Apteco.ApiSystemAnalyser.ApiClient.Model;

namespace Apteco.ApiSystemAnalyser.ApiClient.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IQueriesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// EXPERIMENTAL: Get the query definition in the specified file
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </remarks>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <returns>QueryResult</returns>
        QueryResult QueriesPerformGetQueryFileDefinitionSynchronously (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null);

        /// <summary>
        /// EXPERIMENTAL: Get the query definition in the specified file
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </remarks>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <returns>ApiResponse of QueryResult</returns>
        ApiResponse<QueryResult> QueriesPerformGetQueryFileDefinitionSynchronouslyWithHttpInfo (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null);
        /// <summary>
        /// EXPERIMENTAL: Counts the given query and returns the results
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </remarks>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="query">The query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>QueryResult</returns>
        QueryResult QueriesPerformQueryCountSynchronously (string dataViewName, string systemName, Query query = null, int? timeoutInSeconds = null, bool? returnDefinition = null);

        /// <summary>
        /// EXPERIMENTAL: Counts the given query and returns the results
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </remarks>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="query">The query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>ApiResponse of QueryResult</returns>
        ApiResponse<QueryResult> QueriesPerformQueryCountSynchronouslyWithHttpInfo (string dataViewName, string systemName, Query query = null, int? timeoutInSeconds = null, bool? returnDefinition = null);
        /// <summary>
        /// EXPERIMENTAL: Counts the query in the specified file and returns the results
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </remarks>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>QueryResult</returns>
        QueryResult QueriesPerformQueryFileCountSynchronously (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null, bool? returnDefinition = null);

        /// <summary>
        /// EXPERIMENTAL: Counts the query in the specified file and returns the results
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </remarks>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>ApiResponse of QueryResult</returns>
        ApiResponse<QueryResult> QueriesPerformQueryFileCountSynchronouslyWithHttpInfo (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null, bool? returnDefinition = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// EXPERIMENTAL: Get the query definition in the specified file
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </remarks>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <returns>Task of QueryResult</returns>
        System.Threading.Tasks.Task<QueryResult> QueriesPerformGetQueryFileDefinitionSynchronouslyAsync (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null);

        /// <summary>
        /// EXPERIMENTAL: Get the query definition in the specified file
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </remarks>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <returns>Task of ApiResponse (QueryResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<QueryResult>> QueriesPerformGetQueryFileDefinitionSynchronouslyAsyncWithHttpInfo (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null);
        /// <summary>
        /// EXPERIMENTAL: Counts the given query and returns the results
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </remarks>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="query">The query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>Task of QueryResult</returns>
        System.Threading.Tasks.Task<QueryResult> QueriesPerformQueryCountSynchronouslyAsync (string dataViewName, string systemName, Query query = null, int? timeoutInSeconds = null, bool? returnDefinition = null);

        /// <summary>
        /// EXPERIMENTAL: Counts the given query and returns the results
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </remarks>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="query">The query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>Task of ApiResponse (QueryResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<QueryResult>> QueriesPerformQueryCountSynchronouslyAsyncWithHttpInfo (string dataViewName, string systemName, Query query = null, int? timeoutInSeconds = null, bool? returnDefinition = null);
        /// <summary>
        /// EXPERIMENTAL: Counts the query in the specified file and returns the results
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </remarks>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>Task of QueryResult</returns>
        System.Threading.Tasks.Task<QueryResult> QueriesPerformQueryFileCountSynchronouslyAsync (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null, bool? returnDefinition = null);

        /// <summary>
        /// EXPERIMENTAL: Counts the query in the specified file and returns the results
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </remarks>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>Task of ApiResponse (QueryResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<QueryResult>> QueriesPerformQueryFileCountSynchronouslyAsyncWithHttpInfo (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null, bool? returnDefinition = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class QueriesApi : IQueriesApi
    {
        private Apteco.ApiSystemAnalyser.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="QueriesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public QueriesApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Apteco.ApiSystemAnalyser.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="QueriesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public QueriesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Apteco.ApiSystemAnalyser.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Apteco.ApiSystemAnalyser.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// EXPERIMENTAL: Get the query definition in the specified file EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </summary>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <returns>QueryResult</returns>
        public QueryResult QueriesPerformGetQueryFileDefinitionSynchronously (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null)
        {
             ApiResponse<QueryResult> localVarResponse = QueriesPerformGetQueryFileDefinitionSynchronouslyWithHttpInfo(dataViewName, systemName, queryFile, timeoutInSeconds);
             return localVarResponse.Data;
        }

        /// <summary>
        /// EXPERIMENTAL: Get the query definition in the specified file EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </summary>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <returns>ApiResponse of QueryResult</returns>
        public ApiResponse< QueryResult > QueriesPerformGetQueryFileDefinitionSynchronouslyWithHttpInfo (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling QueriesApi->QueriesPerformGetQueryFileDefinitionSynchronously");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling QueriesApi->QueriesPerformGetQueryFileDefinitionSynchronously");

            var localVarPath = "./{dataViewName}/Queries/{systemName}/GetFileSync";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/xml", 
                "text/xml", 
                "application/_*+xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (timeoutInSeconds != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "timeoutInSeconds", timeoutInSeconds)); // query parameter
            if (queryFile != null && queryFile.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(queryFile); // http body (model) parameter
            }
            else
            {
                localVarPostBody = queryFile; // byte array
            }

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("QueriesPerformGetQueryFileDefinitionSynchronously", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<QueryResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (QueryResult) Configuration.ApiClient.Deserialize(localVarResponse, typeof(QueryResult)));
        }

        /// <summary>
        /// EXPERIMENTAL: Get the query definition in the specified file EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </summary>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <returns>Task of QueryResult</returns>
        public async System.Threading.Tasks.Task<QueryResult> QueriesPerformGetQueryFileDefinitionSynchronouslyAsync (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null)
        {
             ApiResponse<QueryResult> localVarResponse = await QueriesPerformGetQueryFileDefinitionSynchronouslyAsyncWithHttpInfo(dataViewName, systemName, queryFile, timeoutInSeconds);
             return localVarResponse.Data;

        }

        /// <summary>
        /// EXPERIMENTAL: Get the query definition in the specified file EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </summary>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <returns>Task of ApiResponse (QueryResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<QueryResult>> QueriesPerformGetQueryFileDefinitionSynchronouslyAsyncWithHttpInfo (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling QueriesApi->QueriesPerformGetQueryFileDefinitionSynchronously");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling QueriesApi->QueriesPerformGetQueryFileDefinitionSynchronously");

            var localVarPath = "./{dataViewName}/Queries/{systemName}/GetFileSync";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/xml", 
                "text/xml", 
                "application/_*+xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (timeoutInSeconds != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "timeoutInSeconds", timeoutInSeconds)); // query parameter
            if (queryFile != null && queryFile.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(queryFile); // http body (model) parameter
            }
            else
            {
                localVarPostBody = queryFile; // byte array
            }

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("QueriesPerformGetQueryFileDefinitionSynchronously", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<QueryResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (QueryResult) Configuration.ApiClient.Deserialize(localVarResponse, typeof(QueryResult)));
        }

        /// <summary>
        /// EXPERIMENTAL: Counts the given query and returns the results EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </summary>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="query">The query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>QueryResult</returns>
        public QueryResult QueriesPerformQueryCountSynchronously (string dataViewName, string systemName, Query query = null, int? timeoutInSeconds = null, bool? returnDefinition = null)
        {
             ApiResponse<QueryResult> localVarResponse = QueriesPerformQueryCountSynchronouslyWithHttpInfo(dataViewName, systemName, query, timeoutInSeconds, returnDefinition);
             return localVarResponse.Data;
        }

        /// <summary>
        /// EXPERIMENTAL: Counts the given query and returns the results EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </summary>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="query">The query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>ApiResponse of QueryResult</returns>
        public ApiResponse< QueryResult > QueriesPerformQueryCountSynchronouslyWithHttpInfo (string dataViewName, string systemName, Query query = null, int? timeoutInSeconds = null, bool? returnDefinition = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling QueriesApi->QueriesPerformQueryCountSynchronously");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling QueriesApi->QueriesPerformQueryCountSynchronously");

            var localVarPath = "./{dataViewName}/Queries/{systemName}/CountSync";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/xml", 
                "text/xml", 
                "application/_*+xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (timeoutInSeconds != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "timeoutInSeconds", timeoutInSeconds)); // query parameter
            if (returnDefinition != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "returnDefinition", returnDefinition)); // query parameter
            if (query != null && query.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(query); // http body (model) parameter
            }
            else
            {
                localVarPostBody = query; // byte array
            }

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("QueriesPerformQueryCountSynchronously", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<QueryResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (QueryResult) Configuration.ApiClient.Deserialize(localVarResponse, typeof(QueryResult)));
        }

        /// <summary>
        /// EXPERIMENTAL: Counts the given query and returns the results EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </summary>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="query">The query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>Task of QueryResult</returns>
        public async System.Threading.Tasks.Task<QueryResult> QueriesPerformQueryCountSynchronouslyAsync (string dataViewName, string systemName, Query query = null, int? timeoutInSeconds = null, bool? returnDefinition = null)
        {
             ApiResponse<QueryResult> localVarResponse = await QueriesPerformQueryCountSynchronouslyAsyncWithHttpInfo(dataViewName, systemName, query, timeoutInSeconds, returnDefinition);
             return localVarResponse.Data;

        }

        /// <summary>
        /// EXPERIMENTAL: Counts the given query and returns the results EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </summary>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="query">The query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>Task of ApiResponse (QueryResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<QueryResult>> QueriesPerformQueryCountSynchronouslyAsyncWithHttpInfo (string dataViewName, string systemName, Query query = null, int? timeoutInSeconds = null, bool? returnDefinition = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling QueriesApi->QueriesPerformQueryCountSynchronously");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling QueriesApi->QueriesPerformQueryCountSynchronously");

            var localVarPath = "./{dataViewName}/Queries/{systemName}/CountSync";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/xml", 
                "text/xml", 
                "application/_*+xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (timeoutInSeconds != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "timeoutInSeconds", timeoutInSeconds)); // query parameter
            if (returnDefinition != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "returnDefinition", returnDefinition)); // query parameter
            if (query != null && query.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(query); // http body (model) parameter
            }
            else
            {
                localVarPostBody = query; // byte array
            }

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("QueriesPerformQueryCountSynchronously", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<QueryResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (QueryResult) Configuration.ApiClient.Deserialize(localVarResponse, typeof(QueryResult)));
        }

        /// <summary>
        /// EXPERIMENTAL: Counts the query in the specified file and returns the results EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </summary>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>QueryResult</returns>
        public QueryResult QueriesPerformQueryFileCountSynchronously (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null, bool? returnDefinition = null)
        {
             ApiResponse<QueryResult> localVarResponse = QueriesPerformQueryFileCountSynchronouslyWithHttpInfo(dataViewName, systemName, queryFile, timeoutInSeconds, returnDefinition);
             return localVarResponse.Data;
        }

        /// <summary>
        /// EXPERIMENTAL: Counts the query in the specified file and returns the results EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </summary>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>ApiResponse of QueryResult</returns>
        public ApiResponse< QueryResult > QueriesPerformQueryFileCountSynchronouslyWithHttpInfo (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null, bool? returnDefinition = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling QueriesApi->QueriesPerformQueryFileCountSynchronously");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling QueriesApi->QueriesPerformQueryFileCountSynchronously");

            var localVarPath = "./{dataViewName}/Queries/{systemName}/CountFileSync";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/xml", 
                "text/xml", 
                "application/_*+xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (timeoutInSeconds != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "timeoutInSeconds", timeoutInSeconds)); // query parameter
            if (returnDefinition != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "returnDefinition", returnDefinition)); // query parameter
            if (queryFile != null && queryFile.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(queryFile); // http body (model) parameter
            }
            else
            {
                localVarPostBody = queryFile; // byte array
            }

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("QueriesPerformQueryFileCountSynchronously", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<QueryResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (QueryResult) Configuration.ApiClient.Deserialize(localVarResponse, typeof(QueryResult)));
        }

        /// <summary>
        /// EXPERIMENTAL: Counts the query in the specified file and returns the results EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </summary>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>Task of QueryResult</returns>
        public async System.Threading.Tasks.Task<QueryResult> QueriesPerformQueryFileCountSynchronouslyAsync (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null, bool? returnDefinition = null)
        {
             ApiResponse<QueryResult> localVarResponse = await QueriesPerformQueryFileCountSynchronouslyAsyncWithHttpInfo(dataViewName, systemName, queryFile, timeoutInSeconds, returnDefinition);
             return localVarResponse.Data;

        }

        /// <summary>
        /// EXPERIMENTAL: Counts the query in the specified file and returns the results EXPERIMENTAL  Requires licence flags [AdvancedQuery]
        /// </summary>
        /// <exception cref="Apteco.ApiSystemAnalyser.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="queryFile">The file that holds the query definition to count (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the analysis service&#39;s configuration (optional)</param>
        /// <param name="returnDefinition">Whether to include the query&#39;s definition in the results (optional)</param>
        /// <returns>Task of ApiResponse (QueryResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<QueryResult>> QueriesPerformQueryFileCountSynchronouslyAsyncWithHttpInfo (string dataViewName, string systemName, QueryFile queryFile = null, int? timeoutInSeconds = null, bool? returnDefinition = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling QueriesApi->QueriesPerformQueryFileCountSynchronously");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling QueriesApi->QueriesPerformQueryFileCountSynchronously");

            var localVarPath = "./{dataViewName}/Queries/{systemName}/CountFileSync";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/xml", 
                "text/xml", 
                "application/_*+xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (timeoutInSeconds != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "timeoutInSeconds", timeoutInSeconds)); // query parameter
            if (returnDefinition != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "returnDefinition", returnDefinition)); // query parameter
            if (queryFile != null && queryFile.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(queryFile); // http body (model) parameter
            }
            else
            {
                localVarPostBody = queryFile; // byte array
            }

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("QueriesPerformQueryFileCountSynchronously", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<QueryResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (QueryResult) Configuration.ApiClient.Deserialize(localVarResponse, typeof(QueryResult)));
        }

    }
}
